### ISSUE TITLE
DBT commands fail when using non-existent database

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/dbt-clickhouse#70]
Currently if you set the dbt database in the connection parameters and that database does not yet exist (because dbt hasn't created it) `dbt run` and other commands will fail, forcing the user to manually create the special `_dbt` database on the ClickHouse server.  I've also tested setting the database on the newly restored native driver and it also breaks if we set the database to a non-existent database.

Note that setting this database on the driver doesn't actually help the use case of simplifying the SQL because that `_dbt` database is almost completely managed within DBT and the DBT SQL entities normally reference the source database (using `source` macros), not the dbt database, for the initial raw data.  

I suggest we don't even send the database parameter to either driver thereby using the user's default database.   Users can set the default database on the ClickHouse server as desired if they wish to avoid including the database name in DBT SQL.

**Comment by guykoh** [comment]
I don't know if this is the desired behavior. In fact, up until recently we connected always to the default db and asked the clients to always provide the db name in their queries (except of default of course). But then we heard that users don't like that and in general I don't know if that's the expected behavior in dbt.
Maybe if the connection fails because the db doesn't exist we can try to connect with default db and potentially create the target db - wdyt?

**Comment by genzgd** [comment]
We could probably implement this by just doing `CREATE DATABASE {database} IF NOT EXISTS` in `open` method?  It feels a little weird to do that under the covers but since dbt is basically going to do that anyway it might be okay?
