### ISSUE TITLE
dbt run successful even with broken query with 'on cluster'

### ISSUE THREAD

**Issue by simpl1g** [ClickHouse/dbt-clickhouse#83]
If I have query that fails in ClickHouse `dbt run` will still be successful, however there will be an error in ClickHouse and nothing created

```
ClickHouse server 22.3.8.39
dbt-core==1.1.1
dbt-clickhouse==1.1.7
```

Example model
```sql
{{
    config (
      materialized='view',
      cluster='your cluster'
    )
}}

WITH (SELECT * FROM numbers(10)) AS example
SELECT * FROM example
```

dbt run successful
```bash
dbt run --models example

09:29:21  Running with dbt=1.1.1
09:29:21  Found 12 models, 0 tests, 0 snapshots, 0 analyses, 195 macros, 0 operations, 0 seed files, 2 sources, 0 exposures, 0 metrics
09:29:21  
09:29:21  Concurrency: 1 threads (target='dev')
09:29:21  
09:29:21  1 of 1 START view model sample.example ....................................... [RUN]
09:29:22  1 of 1 OK created view model sample.example .................................. [OK in 0.48s]
09:29:22  
09:29:22  Finished running 1 view model in 0.51s.
09:29:22  
09:29:22  Completed successfully
09:29:22  
09:29:22  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

in ClickHouse there is an exception
```bash
type:      ExceptionWhileProcessing
query:     /* {"app": "dbt", "dbt_version": "1.1.1", "profile_name": "sample", "target_name": "dev", "node_id": "model.sample.example"} */


  create view sample.example__dbt_tmp 

  
    on cluster "ch_shards"
  as (
    

WITH (SELECT * FROM numbers(10)) AS example
SELECT * FROM example
  )
exception: Code: 60. DB::Exception: There was an error on [clickhouse-1-2:9000]: Code: 60. DB::Exception: Table default.example doesn't exist. (UNKNOWN_TABLE) (version 22.3.8.39 (official build)). (UNKNOWN_TABLE) (version 22.3.8.39 (official build))
```

**Comment by tema-popov** [comment]
Hi, I found a way to fix it, the problem is in the [clickhouse-connect](https://github.com/tema-popov/clickhouse-connect) dependency, which relies on the HTTP status code for handling errors. 

You can't rely on [clickhouse http status_code response for ON CLUSTER queries](https://github.com/ClickHouse/ClickHouse/issues/15124) without request parameter `wait_end_of_query=1`

It could be an easy fix with a small tweak of `profile.yml`, adding `custom_settings` as in the example:

```yaml
default:
  outputs:
    dev:
      type: clickhouse
      schema: company_db
      host: localhost
      port: 8123
      user: default`
      password: ""
      cluster: company_cluster
      custom_settings:
        wait_end_of_query: 1
      

  target: dev
```

Unfortunately, [clickhouse-connect](https://github.com/tema-popov/clickhouse-connect) has a HTTP parameter validation, that filters `wait_end_of_query` parameter. It looks like a bug.

So, I don't see an easy solution besides fixing [clickhouse-connect](https://github.com/tema-popov/clickhouse-connect)  and updating dependencies in `clickhouse-dbt`.

I will try to prepare fixes both in [clickhouse-connect](https://github.com/tema-popov/clickhouse-connect) and clickhouse-dbt and will share my forks as a temporary solution while fixes are merging.

**Comment by genzgd** [comment]
ClickHouse Connect actually sets wait_end_of_query=1 by default, but @tema-popov correctly identified the bug that was incorrectly filtering it out.  ClickHouse Connect 0.2.4 should contain the fix.  I'll work on getting a new release of clickhouse-dbt out once it's confirmed it will also fix this issue.
